# Site settings
title: My Blog
email: steven.xu13@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my blog.
baseurl: "/blog/" # the subpath of your site, e.g. /blog/
url: "http://sxu.ca" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
